"""
export_utils.py
===============
This module provides data export functionality for the MedScan AI app.

Why in-memory export?
  Streamlit's st.download_button requires data as a string or bytes object.
  We avoid writing to actual disk files because:
  - It keeps the app stateless (no temp file cleanup needed)
  - Works correctly whether the app is run locally or hosted on a server
  - Avoids file permission issues on different operating systems

What can be exported:
  - Medicine data as CSV (single medicine or full database)
  - Medicine data as JSON (structured, for use with other tools)
  - Chatbot conversation transcript as plain text

Author:  Mohammad Fayas Khan
Course:  INT428 — AI Systems Design
Version: 1.0.0
"""


import csv
import json
import io
from datetime import datetime
import logging

import streamlit as st

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
# CSV EXPORT
# ─────────────────────────────────────────────────────────────────────

def medicine_to_csv_string(medicine: dict) -> str:
    """
    Convert a medicine data dict to a CSV-formatted string for download.

    list-type fields are joined with a pipe character '|' to avoid
    conflicting with CSV commas.

    Args:
        medicine (dict): Full medicine data dictionary from database.

    Returns:
        str: CSV-formatted string with header row and one data row.

    Example:
        >>> csv_str = medicine_to_csv_string(paracetamol_dict)
        >>> csv_str.startswith("name,")
        True
    """
    if not medicine:
        return ""

    # Use StringIO as an in-memory buffer for csv.writer
    buffer = io.StringIO()
    writer = csv.writer(buffer)

    # Write header row (column names)
    writer.writerow(list(medicine.keys()))

    # Write data row — flatten list values to pipe-separated strings
    row_values = []
    for val in medicine.values():
        if isinstance(val, list):
            # Join list items with pipe separator (avoids CSV comma conflict)
            row_values.append(" | ".join(str(v) for v in val))
        else:
            row_values.append(str(val) if val is not None else "")

    writer.writerow(row_values)

    # Return the full CSV string content
    return buffer.getvalue()


# ─────────────────────────────────────────────────────────────────────
# JSON EXPORT
# ─────────────────────────────────────────────────────────────────────

def medicine_to_json_string(medicine: dict) -> str:
    """
    Convert a medicine data dict to a formatted JSON string for download.

    Handles non-serialisable types (converts to strings) and formats
    with 2-space indentation for readability.

    Args:
        medicine (dict): Full medicine data dictionary from database.

    Returns:
        str: Pretty-printed JSON string.

    Example:
        >>> json_str = medicine_to_json_string(paracetamol_dict)
        >>> '"name"' in json_str
        True
    """
    if not medicine:
        return "{}"

    # Create a serialisable copy (handle numpy types, etc.)
    safe_dict = {}
    for k, v in medicine.items():
        if isinstance(v, list):
            safe_dict[k] = [str(item) for item in v]
        elif hasattr(v, "item"):
            # NumPy scalar types → native Python
            safe_dict[k] = v.item()
        else:
            safe_dict[k] = str(v) if v is not None else ""

    return json.dumps(safe_dict, indent=2, ensure_ascii=False)


# ─────────────────────────────────────────────────────────────────────
# CHAT HISTORY EXPORT
# ─────────────────────────────────────────────────────────────────────

def chat_history_to_text(history: list, medicine_name: str) -> str:
    """
    Convert a chat history list to a plain-text transcript for download.

    Format:
      ════════════════
      MEDSCAN AI — Chat Transcript
      Medicine: {name}
      Date: {date}
      ════════════════
      [USER]: message
      [MEDBOT]: response
      Detected Intent: {intent}
      ...

    Args:
        history (list[dict]): Chat history list from st.session_state.chat_history.
                              Each entry: {role, text, intent (optional)}.
        medicine_name (str): Name of the medicine being discussed.

    Returns:
        str: Plain-text formatted chat transcript.

    Example:
        >>> transcript = chat_history_to_text(history, "paracetamol")
        >>> "MEDSCAN AI" in transcript
        True
    """
    if not history:
        return "No chat history available."

    # Header block
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "=" * 60,
        "  MEDSCAN AI — Chat Transcript",
        f"  Medicine: {medicine_name.title()}",
        f"  Date: {timestamp}",
        "  Generated by: MEDSCAN AI (Offline Mode)",
        "=" * 60,
        "",
    ]

    # Message blocks
    for i, msg in enumerate(history, 1):
        role = msg.get("role", "unknown").upper()
        text = msg.get("text", "")
        intent = msg.get("intent", "")

        # Format role label
        role_label = "[USER]" if role == "USER" else "[MEDBOT]"
        lines.append(f"{role_label}:")
        lines.append(text)

        # Show detected intent for bot messages
        if role == "BOT" and intent and intent != "unknown":
            lines.append(f"  (Detected Topic: {intent.replace('_', ' ').title()})")

        lines.append("")  # blank line between messages

    # Footer disclaimer
    lines += [
        "-" * 60,
        "DISCLAIMER: This transcript is for informational purposes only.",
        "It does not constitute medical advice. Consult a qualified",
        "healthcare professional before acting on any information here.",
        "-" * 60,
    ]

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────
# STREAMLIT DOWNLOAD BUTTON
# ─────────────────────────────────────────────────────────────────────

def create_download_button(data: str, filename: str,
                           mime: str, label: str) -> None:
    """
    Render a styled Streamlit download button for in-memory data.

    Uses st.download_button — no server storage, purely client-side.
    The button renders inline at the current Streamlit position.

    Args:
        data (str): String data to be downloaded (CSV, JSON, or text).
        filename (str): Suggested filename for the downloaded file.
        mime (str): MIME type string (e.g., "text/csv", "application/json").
        label (str): Button label text displayed to the user.

    Example:
        >>> create_download_button(csv_str, "paracetamol.csv", "text/csv", "⬇ Download CSV")
    """
    # Encode string to bytes for the download button
    data_bytes = data.encode("utf-8")

    # Render styled download button via Streamlit
    st.download_button(
        label=label,
        data=data_bytes,
        file_name=filename,
        mime=mime,
        help=f"Click to download {filename}",
        use_container_width=False,
    )
